name: Deploy StreakForge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Oracle VM
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd ~/StreakForge

            git pull origin main

            cd backend
            npm install

            cd ../frontend
            npm install
            npm run build

            cd ..

            pm2 restart all

            sudo systemctl reload nginx